version: '3.4'

services:
  orchestratordashboard:
    image: giosava94/orchestrator-dashboard
    container_name: orchestratordashboard
    command: sleep infinity
    environment:
      FLASK_DEBUG: 1
      FLASK_SQLALCHEMY_DATABASE_URI: mysql+pymysql://dashboard:${MYSQL_PASSWORD:-changeit}@db:3306/orchestrator_dashboard
      FLASK_REDIS_URL: redis://:${REDIS_PASSWORD:-changeit}@redis:6379
    volumes:
      - ..:/workspace:cached
    networks:
      - dev-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-changeit}
      MYSQL_DATABASE: orchestrator_dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeit}
    networks:
      - dev-network

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - redis-data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeit}
    networks:
      - dev-network

  redis_gui:
    restart: always
    image: redislabs/redisinsight:latest
    container_name: redis-gui
    ports:
      - "8001:8001"
    volumes:
      - redis-db:/db
    networks:
      - dev-network

networks:
  dev-network:


volumes:
  db-data:
  redis-data:
  redis-db:
